defmodule AshTimestamptzError.Repo.Migrations.AddFoos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:foos, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:bar, :timestamptz, null: false)
    end
  end

  def down do
    drop(table(:foos))
  end
end
